//! Core indexing operations

use crate::knowledge::chunking::{ChunkingDispatcher, ChunkingInput};
use crate::knowledge::domain::{
    Chunk, ChunkSource, ChunkableContent, IndexedChunk, LineCount, LineNumber, LineRange, Timestamp,
};

use super::super::{IndexDataProvider, IndexableFile};
use super::types::IndexingError;

use snafu::ResultExt;

/// Convert a domain chunk to an indexed chunk
///
/// Wraps the chunk with index data generated by the provider and timestamp.
pub(super) fn index_chunk(
    chunk: Chunk,
    provider: &dyn IndexDataProvider,
) -> Result<IndexedChunk, IndexingError> {
    use super::types::indexing_error::*;

    let index_data = provider
        .generate(chunk.content.text.as_ref())
        .context(IndexDataGenerationFailedSnafu)?;

    Ok(IndexedChunk::builder()
        .chunk(chunk)
        .index_data(index_data)
        .indexed_at(Timestamp::now())
        .build())
}

/// Process a single file: read, chunk, and index
///
/// Reads the file content, chunks it using the dispatcher, and wraps each chunk
/// with index data.
pub(super) fn process_file(
    file: &IndexableFile,
    dispatcher: &ChunkingDispatcher,
    provider: &dyn IndexDataProvider,
) -> Result<Vec<IndexedChunk>, IndexingError> {
    use super::types::indexing_error::*;

    let content = std::fs::read_to_string(file.absolute_path.to_string())
        .map_err(|e| super::super::ScanError::IoError {
            source: e,
            path: file.absolute_path.to_string(),
        })
        .context(ScanFailedSnafu)?;

    let input = ChunkingInput {
        content: ChunkableContent::new(content),
        source: ChunkSource::builder()
            .file_path(file.relative_path.clone())
            .repo_name(file.repo_name.clone())
            .line_range(
                LineRange::builder()
                    .start(LineNumber::try_new(1).expect("1 is valid line number"))
                    .line_count(LineCount::try_new(1).expect("1 is valid line count"))
                    .build(),
            )
            .build(),
    };

    let chunks = match dispatcher.chunk_file(&input) {
        Some(result) => result.context(ChunkingFailedSnafu)?,
        None => return Ok(vec![]),
    };

    let indexed_chunks = chunks
        .into_iter()
        .map(|chunk| index_chunk(chunk, provider))
        .collect::<Result<Vec<_>, _>>()?;

    Ok(indexed_chunks)
}

#[cfg(test)]
mod test {
    use super::*;
    use crate::knowledge::domain::{
        ChunkContent, ChunkContext, ChunkId, ChunkSource, ForestRelativePath, IndexData,
        MarkdownContext, RepoName, TokenCount,
    };
    use crate::knowledge::indexing::provider::MockIndexDataProvider;

    fn create_test_chunk(file_path: &str, content: &str) -> Chunk {
        Chunk::builder()
            .id(ChunkId::new(uuid::Uuid::new_v4()))
            .source(
                ChunkSource::builder()
                    .file_path(ForestRelativePath::try_new(file_path).unwrap())
                    .repo_name(RepoName::try_new("test-repo").unwrap())
                    .line_range(
                        LineRange::builder()
                            .start(LineNumber::try_new(1).unwrap())
                            .line_count(LineCount::try_new(1).unwrap())
                            .build(),
                    )
                    .build(),
            )
            .content(
                ChunkContent::builder()
                    .text(content.to_string())
                    .token_count(TokenCount::try_new(content.split_whitespace().count()).unwrap())
                    .build(),
            )
            .context(ChunkContext::Markdown(
                MarkdownContext::builder().heading_hierarchy(vec![]).build(),
            ))
            .build()
    }

    #[test]
    fn test_index_chunk_adds_timestamp() {
        // Given A chunk and mock provider
        let chunk = create_test_chunk("test.md", "test content");
        let mut mock_provider = MockIndexDataProvider::new();
        mock_provider.expect_generate().returning(|_| {
            Ok(IndexData::Fast {
                bm25_terms: Default::default(),
            })
        });

        let before = Timestamp::now();

        // When Indexing the chunk
        let indexed = index_chunk(chunk, &mock_provider).unwrap();

        // Then It should have a timestamp
        let after = Timestamp::now();
        assert!(indexed.indexed_at >= before);
        assert!(indexed.indexed_at <= after);
    }

    #[test]
    fn test_index_chunk_calls_provider_generate() {
        // Given A chunk with specific content
        let chunk = create_test_chunk("test.md", "rust programming language");
        let mut mock_provider = MockIndexDataProvider::new();
        mock_provider
            .expect_generate()
            .times(1)
            .withf(|text| text == "rust programming language")
            .returning(|_| {
                Ok(IndexData::Fast {
                    bm25_terms: Default::default(),
                })
            });

        // When Indexing the chunk
        let result = index_chunk(chunk, &mock_provider);

        // Then Provider generate should be called with chunk text
        assert!(result.is_ok());
    }

    #[test]
    fn test_index_chunk_wraps_provider_result() {
        // Given A chunk and provider returning Fast mode data
        let chunk = create_test_chunk("test.md", "test content");
        let mut mock_provider = MockIndexDataProvider::new();
        mock_provider.expect_generate().returning(|_| {
            Ok(IndexData::Fast {
                bm25_terms: Default::default(),
            })
        });

        // When Indexing the chunk
        let indexed = index_chunk(chunk, &mock_provider).unwrap();

        // Then IndexedChunk should contain provider's IndexData
        assert!(matches!(indexed.index_data, IndexData::Fast { .. }));
    }

    #[test]
    fn test_index_chunk_propagates_provider_errors() {
        // Given A chunk and provider that fails
        let chunk = create_test_chunk("test.md", "test content");
        let mut mock_provider = MockIndexDataProvider::new();
        mock_provider.expect_generate().returning(|_| {
            Err(crate::knowledge::indexing::IndexDataError::Bm25Failed {
                source: Box::new(std::io::Error::other("test error")),
            })
        });

        // When Indexing the chunk
        let result = index_chunk(chunk, &mock_provider);

        // Then It should fail with IndexDataGenerationFailed error
        assert!(matches!(
            result,
            Err(IndexingError::IndexDataGenerationFailed { .. })
        ));
    }
}
